# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push events for all branches
  # Triggers the workflow on pull request events but only for the master branch
  push:
    branches: [ master, Playground ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio
          platformio update

      - name: Compile for target
        run: platformio run --environment d1_mini
      
      - name: Perform static checks
        run: platformio check --environment test --skip-packages --fail-on-defect=medium --fail-on-defect=high
      
      - name: Set up graphviz
        uses: ts-graphviz/setup-graphviz@v1.2.0
        
      - name: Set up doxygen and generate documentation
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: './doc/doxygen'
          doxyfile-path: './Doxyfile'

      - name: Check for doxygen warnings
        run: |
          cd ./doc/doxygen
          chmod +x ./checkForWarnings.sh
          ./checkForWarnings.sh
